version: '3.9'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: supporthaiti
      POSTGRES_PASSWORD: supporthaiti
      POSTGRES_DB: supporthaiti
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
